#  Template .NET Core build

#  This template allows you to validate your .NET Core package.
#  The workflow allows running tests and code linting on the default branch.

# To run your pipeline on a Windows machine, create a self-hosted Windows runner.
# For instructions on setting up a Windows runner, see https://support.atlassian.com/bitbucket-cloud/docs/set-up-runners-for-windows/

image: mcr.microsoft.com/dotnet/sdk:6.0

pipelines:
  default:
    - parallel:
        - step:
            name: Build
            caches:
              - dotnetcore
            script:
              - REPORTS_PATH=./build-reports/build_${BITBUCKET_BUILD_NUMBER}
              - dotnet restore
              - dotnet build --no-restore --configuration Release
        - step:
            name: Publish
            caches:
              - dotnetcore
            script:
              - REPORTS_PATH=./publish-reports/build_${BITBUCKET_BUILD_NUMBER}
              - dotnet restore
              - dotnet publish --no-restore --configuration Release
            artifacts:
              - ./publish/**