
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.24.0
//      You can make changes to this file and they will not be overwritten when saving.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace ButterflyCS.Monitor.Wizards {
    using Terminal.Gui;
    
    
    public partial class OpenFile {
        private string filePath = string.Empty; // The file path
        private ushort loadAddress = 0x0000; // The load address

        /// <summary>
        /// Initializes a new instance of the <see cref="OpenFile"/> class.
        /// </summary>
        public OpenFile() {
            InitializeComponent();

            btnLoad.Clicked += () => btnLoad_Clicked();
            btnCancel.Clicked += () => btnCancel_Clicked();
        }

        private void btnLoad_Clicked()
        {
            // Get the file path
            filePath = (string)txtFilePath.Text;

            // Get the address
            loadAddress = Convert.ToUInt16((string)txtLoadAddress.Text, 16);

            // Load the file
            Machine.LoadProgram(filePath, loadAddress);

            // Add the output to the output text view
            MonitorOutput.Add("Loaded file " + filePath + " at address " + loadAddress.ToString("X4"));

            // Close the window
            Application.RequestStop();
        }

        private void btnCancel_Clicked()
        {
            Application.RequestStop();
        }
    }
}
