
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.24.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace ButterflyCS.Monitor.Wizards {
    using System;
    using Terminal.Gui;
    
    
    public partial class OpenFile : Terminal.Gui.Window {
        
        private Terminal.Gui.Label lblFilePath;
        
        private Terminal.Gui.TextField txtFilePath;
        
        private Terminal.Gui.Label lblAddress;
        
        private Terminal.Gui.TextField txtLoadAddress;
        
        private Terminal.Gui.Button btnLoad;
        
        private Terminal.Gui.Button btnCancel;
        
        private void InitializeComponent() {
            this.btnCancel = new Terminal.Gui.Button();
            this.btnLoad = new Terminal.Gui.Button();
            this.txtLoadAddress = new Terminal.Gui.TextField();
            this.lblAddress = new Terminal.Gui.Label();
            this.txtFilePath = new Terminal.Gui.TextField();
            this.lblFilePath = new Terminal.Gui.Label();
            this.Width = Dim.Percent(50f);
            this.Height = 8;
            this.X = Pos.Center();
            this.Y = Pos.Center();
            this.Modal = true;
            this.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.Border.BorderBrush = Terminal.Gui.Color.White;
            this.Border.Effect3D = false;
            this.Border.Effect3DBrush = null;
            this.Border.DrawMarginFrame = true;
            this.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Title = "Load File";
            this.lblFilePath.Width = 4;
            this.lblFilePath.Height = 1;
            this.lblFilePath.X = 0;
            this.lblFilePath.Y = 0;
            this.lblFilePath.Data = "lblFilePath";
            this.lblFilePath.Text = "File Path:";
            this.lblFilePath.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.lblFilePath);
            this.txtFilePath.Width = Dim.Percent(96f);
            this.txtFilePath.Height = 1;
            this.txtFilePath.X = 11;
            this.txtFilePath.Y = 0;
            this.txtFilePath.Secret = false;
            this.txtFilePath.Data = "txtFilePath";
            this.txtFilePath.Text = "";
            this.txtFilePath.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.txtFilePath);
            this.lblAddress.Width = Dim.Percent(4f);
            this.lblAddress.Height = 1;
            this.lblAddress.X = 0;
            this.lblAddress.Y = Pos.Bottom(lblFilePath) + 1;
            this.lblAddress.Data = "lblAddress";
            this.lblAddress.Text = "Address:";
            this.lblAddress.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.lblAddress);
            this.txtLoadAddress.Width = Dim.Percent(96f);
            this.txtLoadAddress.Height = 1;
            this.txtLoadAddress.X = Pos.Right(lblAddress) + 3;
            this.txtLoadAddress.Y = 2;
            this.txtLoadAddress.Secret = false;
            this.txtLoadAddress.Data = "txtLoadAddress";
            this.txtLoadAddress.Text = "";
            this.txtLoadAddress.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.txtLoadAddress);
            this.btnLoad.Width = 8;
            this.btnLoad.Height = 1;
            this.btnLoad.X = 39;
            this.btnLoad.Y = 5;
            this.btnLoad.Data = "btnLoad";
            this.btnLoad.Text = "Load";
            this.btnLoad.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.btnLoad.IsDefault = false;
            this.Add(this.btnLoad);
            this.btnCancel.Width = 10;
            this.btnCancel.Height = 1;
            this.btnCancel.X = 48;
            this.btnCancel.Y = 5;
            this.btnCancel.Data = "btnCancel";
            this.btnCancel.Text = "Cancel";
            this.btnCancel.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.btnCancel.IsDefault = false;
            this.Add(this.btnCancel);
        }
    }
}
