
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.24.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace ButterflyCS.Monitor {
    using System;
    using Terminal.Gui;
    
    
    public partial class MonitorWindow : Terminal.Gui.Toplevel {
        
        private Terminal.Gui.ColorScheme greenOnBlack;
        
        private Terminal.Gui.ColorScheme blueOnBlack;
        
        private Terminal.Gui.ColorScheme tgDefault;
        
        private Terminal.Gui.Window outputWindow;
        
        private Terminal.Gui.TextView txtOutput;
        
        private Terminal.Gui.Window controlsWindow;
        
        private Terminal.Gui.TextField txtCommand;
        
        private Terminal.Gui.Button btnRun;
        
        private Terminal.Gui.Button btnPause;
        
        private Terminal.Gui.Button btnStep;
        
        private Terminal.Gui.Button btnReset;
        
        private Terminal.Gui.Button btnLoad;
        
        private Terminal.Gui.Button btnQuit;
        
        private Terminal.Gui.Window registersWindow;
        
        private Terminal.Gui.Label lblRegA;
        
        private Terminal.Gui.TextField txtA;
        
        private Terminal.Gui.Label lblX;
        
        private Terminal.Gui.TextField txtX;
        
        private Terminal.Gui.Label lblY;
        
        private Terminal.Gui.TextField txtY;
        
        private Terminal.Gui.Label lblSP;
        
        private Terminal.Gui.TextField txtSP;
        
        private Terminal.Gui.Label lblPC;
        
        private Terminal.Gui.TextField txtPC;
        
        private Terminal.Gui.Label lblStatus;
        
        private Terminal.Gui.TextField txtStatus;
        
        private Terminal.Gui.Label lblCycles;
        
        private Terminal.Gui.TextField txtCycles;
        
        private void InitializeComponent() {
            this.txtCycles = new Terminal.Gui.TextField();
            this.lblCycles = new Terminal.Gui.Label();
            this.txtStatus = new Terminal.Gui.TextField();
            this.lblStatus = new Terminal.Gui.Label();
            this.txtPC = new Terminal.Gui.TextField();
            this.lblPC = new Terminal.Gui.Label();
            this.txtSP = new Terminal.Gui.TextField();
            this.lblSP = new Terminal.Gui.Label();
            this.txtY = new Terminal.Gui.TextField();
            this.lblY = new Terminal.Gui.Label();
            this.txtX = new Terminal.Gui.TextField();
            this.lblX = new Terminal.Gui.Label();
            this.txtA = new Terminal.Gui.TextField();
            this.lblRegA = new Terminal.Gui.Label();
            this.registersWindow = new Terminal.Gui.Window();
            this.btnQuit = new Terminal.Gui.Button();
            this.btnLoad = new Terminal.Gui.Button();
            this.btnReset = new Terminal.Gui.Button();
            this.btnStep = new Terminal.Gui.Button();
            this.btnPause = new Terminal.Gui.Button();
            this.btnRun = new Terminal.Gui.Button();
            this.txtCommand = new Terminal.Gui.TextField();
            this.controlsWindow = new Terminal.Gui.Window();
            this.txtOutput = new Terminal.Gui.TextView();
            this.outputWindow = new Terminal.Gui.Window();
            this.greenOnBlack = new Terminal.Gui.ColorScheme();
            this.greenOnBlack.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.Green, Terminal.Gui.Color.Black);
            this.greenOnBlack.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightGreen, Terminal.Gui.Color.Black);
            this.greenOnBlack.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Green, Terminal.Gui.Color.Magenta);
            this.greenOnBlack.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightGreen, Terminal.Gui.Color.Magenta);
            this.greenOnBlack.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.Gray, Terminal.Gui.Color.Black);
            this.blueOnBlack = new Terminal.Gui.ColorScheme();
            this.blueOnBlack.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightBlue, Terminal.Gui.Color.Black);
            this.blueOnBlack.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.Cyan, Terminal.Gui.Color.Black);
            this.blueOnBlack.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightBlue, Terminal.Gui.Color.BrightYellow);
            this.blueOnBlack.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Cyan, Terminal.Gui.Color.BrightYellow);
            this.blueOnBlack.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.Gray, Terminal.Gui.Color.Black);
            this.tgDefault = new Terminal.Gui.ColorScheme();
            this.tgDefault.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Blue);
            this.tgDefault.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightCyan, Terminal.Gui.Color.Blue);
            this.tgDefault.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.Gray);
            this.tgDefault.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightBlue, Terminal.Gui.Color.Gray);
            this.tgDefault.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.Brown, Terminal.Gui.Color.Blue);
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Modal = false;
            this.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.outputWindow.Width = 120;
            this.outputWindow.Height = 24;
            this.outputWindow.X = 0;
            this.outputWindow.Y = 0;
            this.outputWindow.Modal = false;
            this.outputWindow.Data = "outputWindow";
            this.outputWindow.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.outputWindow.Border.BorderBrush = Terminal.Gui.Color.White;
            this.outputWindow.Border.Effect3D = false;
            this.outputWindow.Border.Effect3DBrush = null;
            this.outputWindow.Border.DrawMarginFrame = true;
            this.outputWindow.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.outputWindow.Title = "Output";
            this.Add(this.outputWindow);
            this.txtOutput.Width = Dim.Percent(100f) + 2;
            this.txtOutput.Height = Dim.Percent(100f) + 2;
            this.txtOutput.X = 0;
            this.txtOutput.Y = 0;
            this.txtOutput.ColorScheme = this.tgDefault;
            this.txtOutput.AllowsTab = true;
            this.txtOutput.AllowsReturn = true;
            this.txtOutput.WordWrap = false;
            this.txtOutput.Data = "txtOutput";
            this.txtOutput.Text = "";
            this.txtOutput.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.outputWindow.Add(this.txtOutput);
            this.controlsWindow.Width = 80;
            this.controlsWindow.Height = 6;
            this.controlsWindow.X = 0;
            this.controlsWindow.Y = 24;
            this.controlsWindow.Modal = false;
            this.controlsWindow.Data = "controlsWindow";
            this.controlsWindow.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.controlsWindow.Border.BorderBrush = Terminal.Gui.Color.White;
            this.controlsWindow.Border.Effect3D = false;
            this.controlsWindow.Border.Effect3DBrush = null;
            this.controlsWindow.Border.DrawMarginFrame = true;
            this.controlsWindow.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.controlsWindow.Title = "Controls";
            this.Add(this.controlsWindow);
            this.txtCommand.Width = Dim.Percent(100f) + 2;
            this.txtCommand.Height = 2;
            this.txtCommand.X = 0;
            this.txtCommand.Y = 1;
            this.txtCommand.Secret = false;
            this.txtCommand.Data = "txtCommand";
            this.txtCommand.Text = "";
            this.txtCommand.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.controlsWindow.Add(this.txtCommand);
            this.btnRun.Width = 7;
            this.btnRun.Height = 1;
            this.btnRun.X = 0;
            this.btnRun.Y = 3;
            this.btnRun.Data = "btnRun";
            this.btnRun.Text = "Run";
            this.btnRun.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.btnRun.IsDefault = false;
            this.controlsWindow.Add(this.btnRun);
            this.btnPause.Width = 9;
            this.btnPause.Height = 1;
            this.btnPause.X = 9;
            this.btnPause.Y = 3;
            this.btnPause.Data = "btnPause";
            this.btnPause.Text = "Pause";
            this.btnPause.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.btnPause.IsDefault = false;
            this.controlsWindow.Add(this.btnPause);
            this.btnStep.Width = 8;
            this.btnStep.Height = 1;
            this.btnStep.X = 20;
            this.btnStep.Y = 3;
            this.btnStep.Data = "btnStep";
            this.btnStep.Text = "Step";
            this.btnStep.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.btnStep.IsDefault = false;
            this.controlsWindow.Add(this.btnStep);
            this.btnReset.Width = 9;
            this.btnReset.Height = 1;
            this.btnReset.X = 30;
            this.btnReset.Y = 3;
            this.btnReset.Data = "btnReset";
            this.btnReset.Text = "Reset";
            this.btnReset.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.btnReset.IsDefault = false;
            this.controlsWindow.Add(this.btnReset);
            this.btnLoad.Width = 8;
            this.btnLoad.Height = 1;
            this.btnLoad.X = 41;
            this.btnLoad.Y = 3;
            this.btnLoad.Data = "btnLoad";
            this.btnLoad.Text = "Load";
            this.btnLoad.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.btnLoad.IsDefault = false;
            this.controlsWindow.Add(this.btnLoad);
            this.btnQuit.Width = 8;
            this.btnQuit.Height = 1;
            this.btnQuit.X = 51;
            this.btnQuit.Y = 3;
            this.btnQuit.Data = "btnQuit";
            this.btnQuit.Text = "Quit";
            this.btnQuit.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.btnQuit.IsDefault = false;
            this.controlsWindow.Add(this.btnQuit);
            this.registersWindow.Width = 40;
            this.registersWindow.Height = 6;
            this.registersWindow.X = 80;
            this.registersWindow.Y = 24;
            this.registersWindow.Modal = false;
            this.registersWindow.Data = "registersWindow";
            this.registersWindow.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.registersWindow.Border.BorderBrush = Terminal.Gui.Color.White;
            this.registersWindow.Border.Effect3D = false;
            this.registersWindow.Border.Effect3DBrush = null;
            this.registersWindow.Border.DrawMarginFrame = true;
            this.registersWindow.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.registersWindow.Title = "Registers";
            this.Add(this.registersWindow);
            this.lblRegA.Width = 1;
            this.lblRegA.Height = 1;
            this.lblRegA.X = 3;
            this.lblRegA.Y = 1;
            this.lblRegA.Data = "lblRegA";
            this.lblRegA.Text = "A";
            this.lblRegA.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.registersWindow.Add(this.lblRegA);
            this.txtA.Width = 2;
            this.txtA.Height = 1;
            this.txtA.X = 5;
            this.txtA.Y = 1;
            this.txtA.Secret = false;
            this.txtA.Data = "txtA";
            this.txtA.Text = "";
            this.txtA.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.registersWindow.Add(this.txtA);
            this.lblX.Width = 1;
            this.lblX.Height = 1;
            this.lblX.X = 9;
            this.lblX.Y = 1;
            this.lblX.Data = "lblX";
            this.lblX.Text = "X";
            this.lblX.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.registersWindow.Add(this.lblX);
            this.txtX.Width = 2;
            this.txtX.Height = 1;
            this.txtX.X = 11;
            this.txtX.Y = 1;
            this.txtX.Secret = false;
            this.txtX.Data = "txtX";
            this.txtX.Text = "";
            this.txtX.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.registersWindow.Add(this.txtX);
            this.lblY.Width = 1;
            this.lblY.Height = 1;
            this.lblY.X = 15;
            this.lblY.Y = 1;
            this.lblY.Data = "lblY";
            this.lblY.Text = "Y";
            this.lblY.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.registersWindow.Add(this.lblY);
            this.txtY.Width = 2;
            this.txtY.Height = 2;
            this.txtY.X = 17;
            this.txtY.Y = 1;
            this.txtY.Secret = false;
            this.txtY.Data = "txtY";
            this.txtY.Text = "";
            this.txtY.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.registersWindow.Add(this.txtY);
            this.lblSP.Width = 1;
            this.lblSP.Height = 1;
            this.lblSP.X = 21;
            this.lblSP.Y = 1;
            this.lblSP.Data = "lblSP";
            this.lblSP.Text = "SP";
            this.lblSP.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.registersWindow.Add(this.lblSP);
            this.txtSP.Width = 2;
            this.txtSP.Height = 1;
            this.txtSP.X = 24;
            this.txtSP.Y = 1;
            this.txtSP.Secret = false;
            this.txtSP.Data = "txtSP";
            this.txtSP.Text = "";
            this.txtSP.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.registersWindow.Add(this.txtSP);
            this.lblPC.Width = 3;
            this.lblPC.Height = 1;
            this.lblPC.X = 28;
            this.lblPC.Y = 1;
            this.lblPC.Data = "lblPC";
            this.lblPC.Text = "PC";
            this.lblPC.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.registersWindow.Add(this.lblPC);
            this.txtPC.Width = 4;
            this.txtPC.Height = 1;
            this.txtPC.X = 31;
            this.txtPC.Y = 1;
            this.txtPC.Secret = false;
            this.txtPC.Data = "txtPC";
            this.txtPC.Text = "";
            this.txtPC.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.registersWindow.Add(this.txtPC);
            this.lblStatus.Width = 5;
            this.lblStatus.Height = 1;
            this.lblStatus.X = 4;
            this.lblStatus.Y = 3;
            this.lblStatus.Data = "lblStatus";
            this.lblStatus.Text = "Status";
            this.lblStatus.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.registersWindow.Add(this.lblStatus);
            this.txtStatus.Width = 8;
            this.txtStatus.Height = 1;
            this.txtStatus.X = 11;
            this.txtStatus.Y = 3;
            this.txtStatus.Secret = false;
            this.txtStatus.Data = "txtStatus";
            this.txtStatus.Text = "";
            this.txtStatus.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.registersWindow.Add(this.txtStatus);
            this.lblCycles.Width = 4;
            this.lblCycles.Height = 1;
            this.lblCycles.X = 21;
            this.lblCycles.Y = 3;
            this.lblCycles.Data = "lblCycles";
            this.lblCycles.Text = "Cycles";
            this.lblCycles.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.registersWindow.Add(this.lblCycles);
            this.txtCycles.Width = 4;
            this.txtCycles.Height = 1;
            this.txtCycles.X = 28;
            this.txtCycles.Y = 3;
            this.txtCycles.Secret = false;
            this.txtCycles.Data = "txtCycles";
            this.txtCycles.Text = "";
            this.txtCycles.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.registersWindow.Add(this.txtCycles);
        }
    }
}
