
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.24.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace ButterflyCS.Monitor {
    using System;
    using Terminal.Gui;


#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
    public partial class MonitorWindow : Terminal.Gui.Window {
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member

        private Terminal.Gui.ColorScheme blueOnBlack;
        
        private Terminal.Gui.TextView txtOutput;
        
        private Terminal.Gui.Label lblCommand;
        
        private Terminal.Gui.TextField txtCommand;
        
        private Terminal.Gui.Label lblRegA;
        
        private Terminal.Gui.TextField txtRegA;
        
        private Terminal.Gui.Label lblRegX;
        
        private Terminal.Gui.TextField txtRegX;
        
        private Terminal.Gui.Label lblRegY;
        
        private Terminal.Gui.TextField txtRegY;
        
        private Terminal.Gui.Label lblRegSP;
        
        private Terminal.Gui.TextField txtRegSP;
        
        private Terminal.Gui.Label lblRegPC;
        
        private Terminal.Gui.TextField txtRegPC;
        
        private Terminal.Gui.Label lblRegStatus;
        
        private Terminal.Gui.TextField txtRegStatus;
        
        private Terminal.Gui.MenuBar menuBar;
        
        private Terminal.Gui.MenuBarItem fileMenu;
        
        private Terminal.Gui.MenuItem openbinMenuItem;
        
        private Terminal.Gui.MenuItem quitMenuItem;
        
        private Terminal.Gui.MenuBarItem controlMenu;
        
        private Terminal.Gui.MenuItem runMenuItem;
        
        private Terminal.Gui.MenuItem pauseMenuItem;
        
        private Terminal.Gui.MenuItem resetMenuItem;
        
        private Terminal.Gui.MenuItem stepMenuItem;
        
        private Terminal.Gui.MenuBarItem helpMenu;
        
        private Terminal.Gui.MenuItem aboutButterflyMenuItem;
        
        private void InitializeComponent() {
            this.menuBar = new Terminal.Gui.MenuBar();
            this.txtRegStatus = new Terminal.Gui.TextField();
            this.lblRegStatus = new Terminal.Gui.Label();
            this.txtRegPC = new Terminal.Gui.TextField();
            this.lblRegPC = new Terminal.Gui.Label();
            this.txtRegSP = new Terminal.Gui.TextField();
            this.lblRegSP = new Terminal.Gui.Label();
            this.txtRegY = new Terminal.Gui.TextField();
            this.lblRegY = new Terminal.Gui.Label();
            this.txtRegX = new Terminal.Gui.TextField();
            this.lblRegX = new Terminal.Gui.Label();
            this.txtRegA = new Terminal.Gui.TextField();
            this.lblRegA = new Terminal.Gui.Label();
            this.txtCommand = new Terminal.Gui.TextField();
            this.lblCommand = new Terminal.Gui.Label();
            this.txtOutput = new Terminal.Gui.TextView();
            this.blueOnBlack = new Terminal.Gui.ColorScheme();
            this.blueOnBlack.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightBlue, Terminal.Gui.Color.Black);
            this.blueOnBlack.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.Cyan, Terminal.Gui.Color.Black);
            this.blueOnBlack.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightBlue, Terminal.Gui.Color.BrightYellow);
            this.blueOnBlack.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Cyan, Terminal.Gui.Color.BrightYellow);
            this.blueOnBlack.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.Gray, Terminal.Gui.Color.Black);
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Modal = false;
            this.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.Border.BorderBrush = Terminal.Gui.Color.White;
            this.Border.Effect3D = false;
            this.Border.Effect3DBrush = null;
            this.Border.DrawMarginFrame = true;
            this.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Title = "";
            this.txtOutput.Width = Dim.Percent(100f);
            this.txtOutput.Height = Dim.Percent(85f);
            this.txtOutput.X = 0;
            this.txtOutput.Y = 1;
            this.txtOutput.ColorScheme = this.blueOnBlack;
            this.txtOutput.AllowsTab = true;
            this.txtOutput.AllowsReturn = true;
            this.txtOutput.WordWrap = false;
            this.txtOutput.Data = "txtOutput";
            this.txtOutput.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.txtOutput);
            this.lblCommand.Width = 4;
            this.lblCommand.Height = 1;
            this.lblCommand.X = 0;
            this.lblCommand.Y = Pos.Bottom(txtOutput) + 1;
            this.lblCommand.Data = "lblCommand";
            this.lblCommand.Text = "Command:";
            this.lblCommand.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.lblCommand);
            this.txtCommand.Width = 38;
            this.txtCommand.Height = 1;
            this.txtCommand.X = 9;
            this.txtCommand.Y = Pos.Bottom(txtOutput) + 1;
            this.txtCommand.Secret = false;
            this.txtCommand.Data = "txtCommand";
            this.txtCommand.Text = "";
            this.txtCommand.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.txtCommand);
            this.lblRegA.Width = 2;
            this.lblRegA.Height = 1;
            this.lblRegA.X = 0;
            this.lblRegA.Y = Pos.Bottom(lblCommand) + 1;
            this.lblRegA.Data = "lblRegA";
            this.lblRegA.Text = "A:";
            this.lblRegA.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.lblRegA);
            this.txtRegA.Width = 2;
            this.txtRegA.Height = 1;
            this.txtRegA.X = Pos.Right(lblRegA);
            this.txtRegA.Y = Pos.Bottom(lblCommand) + 1;
            this.txtRegA.Secret = false;
            this.txtRegA.Data = "txtRegA";
            this.txtRegA.Text = "";
            this.txtRegA.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.txtRegA);
            this.lblRegX.Width = 1;
            this.lblRegX.Height = 1;
            this.lblRegX.X = Pos.Right(txtRegA) + 2;
            this.lblRegX.Y = Pos.Bottom(lblCommand) + 1;
            this.lblRegX.Data = "lblRegX";
            this.lblRegX.Text = "X:";
            this.lblRegX.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.lblRegX);
            this.txtRegX.Width = 2;
            this.txtRegX.Height = 1;
            this.txtRegX.X = Pos.Right(lblRegX);
            this.txtRegX.Y = Pos.Bottom(lblCommand) + 1;
            this.txtRegX.Secret = false;
            this.txtRegX.Data = "txtRegX";
            this.txtRegX.Text = "";
            this.txtRegX.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.txtRegX);
            this.lblRegY.Width = 1;
            this.lblRegY.Height = 1;
            this.lblRegY.X = Pos.Right(txtRegX) + 2;
            this.lblRegY.Y = Pos.Bottom(lblCommand) + 1;
            this.lblRegY.Data = "lblRegY";
            this.lblRegY.Text = "Y:";
            this.lblRegY.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.lblRegY);
            this.txtRegY.Width = 2;
            this.txtRegY.Height = 1;
            this.txtRegY.X = Pos.Right(lblRegY);
            this.txtRegY.Y = Pos.Bottom(lblCommand) + 1;
            this.txtRegY.Secret = false;
            this.txtRegY.Data = "txtRegY";
            this.txtRegY.Text = "";
            this.txtRegY.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.txtRegY);
            this.lblRegSP.Width = 2;
            this.lblRegSP.Height = 1;
            this.lblRegSP.X = Pos.Right(txtRegY) + 2;
            this.lblRegSP.Y = Pos.Bottom(lblCommand) + 1;
            this.lblRegSP.Data = "lblRegSP";
            this.lblRegSP.Text = "SP:";
            this.lblRegSP.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.lblRegSP);
            this.txtRegSP.Width = 2;
            this.txtRegSP.Height = 1;
            this.txtRegSP.X = Pos.Right(lblRegSP);
            this.txtRegSP.Y = Pos.Bottom(lblCommand) + 1;
            this.txtRegSP.Secret = false;
            this.txtRegSP.Data = "txtRegSP";
            this.txtRegSP.Text = "";
            this.txtRegSP.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.txtRegSP);
            this.lblRegPC.Width = 3;
            this.lblRegPC.Height = 1;
            this.lblRegPC.X = Pos.Right(txtRegSP) + 2;
            this.lblRegPC.Y = Pos.Bottom(lblCommand) + 1;
            this.lblRegPC.Data = "lblRegPC";
            this.lblRegPC.Text = "PC:";
            this.lblRegPC.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.lblRegPC);
            this.txtRegPC.Width = 4;
            this.txtRegPC.Height = 1;
            this.txtRegPC.X = Pos.Right(lblRegPC);
            this.txtRegPC.Y = Pos.Bottom(lblCommand) + 1;
            this.txtRegPC.Secret = false;
            this.txtRegPC.Data = "txtRegPC";
            this.txtRegPC.Text = "";
            this.txtRegPC.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.txtRegPC);
            this.lblRegStatus.Width = 4;
            this.lblRegStatus.Height = 1;
            this.lblRegStatus.X = Pos.Right(txtRegPC) + 2;
            this.lblRegStatus.Y = Pos.Bottom(lblCommand) + 1;
            this.lblRegStatus.Data = "lblRegStatus";
            this.lblRegStatus.Text = "Status:";
            this.lblRegStatus.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.lblRegStatus);
            this.txtRegStatus.Width = 8;
            this.txtRegStatus.Height = 1;
            this.txtRegStatus.X = Pos.Right(lblRegStatus);
            this.txtRegStatus.Y = Pos.Bottom(lblCommand) + 1;
            this.txtRegStatus.Secret = false;
            this.txtRegStatus.Data = "txtRegStatus";
            this.txtRegStatus.Text = "";
            this.txtRegStatus.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.txtRegStatus);
            this.menuBar.Width = Dim.Fill(0);
            this.menuBar.Height = 1;
            this.menuBar.X = 0;
            this.menuBar.Y = 0;
            this.menuBar.Data = "menuBar";
            this.menuBar.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.fileMenu = new Terminal.Gui.MenuBarItem();
            this.fileMenu.Title = "_File";
            this.openbinMenuItem = new Terminal.Gui.MenuItem();
            this.openbinMenuItem.Title = "_Open .bin";
            this.openbinMenuItem.Data = "openbinMenuItem";
            this.quitMenuItem = new Terminal.Gui.MenuItem();
            this.quitMenuItem.Title = "_Quit";
            this.quitMenuItem.Data = "quitMenuItem";
            this.fileMenu.Children = new Terminal.Gui.MenuItem[] {
                    this.openbinMenuItem,
                    this.quitMenuItem};
            this.controlMenu = new Terminal.Gui.MenuBarItem();
            this.controlMenu.Title = "_Control";
            this.runMenuItem = new Terminal.Gui.MenuItem();
            this.runMenuItem.Title = "Run";
            this.runMenuItem.Data = "runMenuItem";
            this.pauseMenuItem = new Terminal.Gui.MenuItem();
            this.pauseMenuItem.Title = "_Pause";
            this.pauseMenuItem.Data = "pauseMenuItem";
            this.resetMenuItem = new Terminal.Gui.MenuItem();
            this.resetMenuItem.Title = "_Reset";
            this.resetMenuItem.Data = "resetMenuItem";
            this.stepMenuItem = new Terminal.Gui.MenuItem();
            this.stepMenuItem.Title = "_Step";
            this.stepMenuItem.Data = "stepMenuItem";
            this.controlMenu.Children = new Terminal.Gui.MenuItem[] {
                    this.runMenuItem,
                    this.pauseMenuItem,
                    this.resetMenuItem,
                    this.stepMenuItem};
            this.helpMenu = new Terminal.Gui.MenuBarItem();
            this.helpMenu.Title = "_Help";
            this.aboutButterflyMenuItem = new Terminal.Gui.MenuItem();
            this.aboutButterflyMenuItem.Title = "_About Butterfly";
            this.aboutButterflyMenuItem.Data = "aboutButterflyMenuItem";
            this.helpMenu.Children = new Terminal.Gui.MenuItem[] {
                    this.aboutButterflyMenuItem};
            this.menuBar.Menus = new Terminal.Gui.MenuBarItem[] {
                    this.fileMenu,
                    this.controlMenu,
                    this.helpMenu};
            this.Add(this.menuBar);
        }
    }
}
